version: 2
jobs:
  build:
    docker:
      - image: docker:stable
    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Publishing Docker Hub images
          command: find . -name Dockerfile -exec ~/repo/build.sh {} \+
